### ISSUE TITLE
Commit missing

### ISSUE THREAD

**Issue by c0deWiZz** [albedoklaus/ibnss2020#1]
The commit from salpeterklaus is still missing, let's look into this soon!

**Comment by albedoklaus** [comment]
:middle_finger:

**Comment by c0deWiZz** [comment]
Sehr geehrter Herr Klaus, da können wir doch wohl zivilisiert drüber reden??? Entschuldigung bitte!

**Comment by albedoklaus** [comment]
Haha, ich kann deine Beiträge löschen

**Comment by c0deWiZz** [comment]
Wo ist mein Beitrag?????
